remote_theme: just-the-docs/just-the-docs
logo: "/assets/opengolf.png"

footer_content: 'Copyright &copy; 2023 OpenGolf - <a href="/privacy">Privacy</a>'

callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: yellow
  error:
    title: Error
    color: red
