remote_theme: just-the-docs/just-the-docs
logo: "/assets/opengolf.png"

footer_content: 'Copyright &copy; 2023 OpenGolf - <a href="/privacy">Privacy</a>'
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y"

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.6.1"

callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: yellow
  error:
    title: Error
    color: red
